### PR TITLE
Submission for task 1 - Abhishek

### PR DESCRIPTION
**Pull request by abhishekshree**
This is my submission for task 1. The filename is "AbhishekShree.md".

### CODE REVIEW

**Comment by shubhamkorde** [comment]
Whenever you send any PR, make sure to add you add a detailed description.

**Review by shubhamkorde — APPROVED** [review]
Great Job!

**Comment by abhishekshree** [comment]
Oh, okay sorry. Should I close this one an send again ?

**Comment by shubhamkorde** [comment]
You can update this PR. No need to send a new one. There must be an edit option somewhere. Find it.

**Review by shubhamkorde — CHANGES_REQUESTED** [review]
Also, rename the file to AbhishekShree.md

**Comment by abhishekshree** [comment]
I renamed the file. Is it reflecting in this PR ?

**Comment by shubhamkorde** [comment]
Another thing. Once you make a change, make sure you assign one of the reviewers. Do not forget to resolve any conversations. Try doing this now.

**Comment by abhishekshree** [comment]
Like this ?

**Review by shubhamkorde — APPROVED** [review]

**Comment by shubhamkorde** [comment]
A good practice is to delete that branch from your fork once your PR has got merged.

**Pull request merged**
